const styles = [
    {name: "Abstrait"},
    {name: "Aquarelle"},
    {name: "Biomecanique"},
    {name: "Blackwork"},
    {name: "Cartoon"},
    {name: "Couleurs"},
    {name: "Dotwork"},
    {name: "Floral"},
    {name: "Graphique abstrait"},
    {name: "Gravure"},
    {name: "Illustratif"},
    {name: "Japonais"},
    {name: "Lettering"},
    {name: "Manga"},
    {name: "Neotrad"},
    {name: "Noir & Gris"},
    {name: "Ornemental / Graphique"},
    {name: "Polynésien"},
    {name: "Réalisme"},
    {name: "Thaïlandais traditionnel"},
    {name: "Traditionnel / New School"},
    {name: "Uncategorized"},
]